version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_keycloak
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_net
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.4
    container_name: keycloak_server
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: 123456
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 123456
      KC_HOSTNAME: localhost
    ports:
      - "8080:8080"
    networks:
      - keycloak_net
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  keycloak_net:

volumes:
  postgres_data: